// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Mf26z-uJvKaH3ZaRtWsWn_jDGchnnKw',
    appId: '1:77560393674:web:3ccef177dafb405a51a933',
    messagingSenderId: '77560393674',
    projectId: 'firanalysis',
    authDomain: 'firanalysis.firebaseapp.com',
    storageBucket: 'firanalysis.appspot.com',
    measurementId: 'G-L0LMQPMCC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxb0KZcAe-HRsYIiz8QbeKEB8yh4Ud_c',
    appId: '1:77560393674:android:9972270692ce276751a933',
    messagingSenderId: '77560393674',
    projectId: 'firanalysis',
    storageBucket: 'firanalysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQpNj6bIFTfBQQ4uR0q4zSx2w71Euzs0',
    appId: '1:77560393674:ios:023a4a7c713751fd51a933',
    messagingSenderId: '77560393674',
    projectId: 'firanalysis',
    storageBucket: 'firanalysis.appspot.com',
    iosBundleId: 'com.example.firAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQpNj6bIFTfBQQ4uR0q4zSx2w71Euzs0',
    appId: '1:77560393674:ios:dea72176a5f5233b51a933',
    messagingSenderId: '77560393674',
    projectId: 'firanalysis',
    storageBucket: 'firanalysis.appspot.com',
    iosBundleId: 'com.example.firAnalysis.RunnerTests',
  );
}
